### PR TITLE
Added a TriangleShape class to sofia-graphics.

### PR DESCRIPTION
**Pull request by rjschof**
As a part of the group project for CS 2114, I made a class that adds triangles to the screen. 

When I was working on the project for 2114, I was having difficulty getting the PolygonShape class to do everything I wanted it to do (outlines of the shapes, for example). Adding this class to the sofia-graphics project would allow students to make use of triangles for their applications for android.

### CODE REVIEW

**Comment by allevato** [comment]
Robert, thanks for contributing! I've left some feedback that you should consider applying in order to improve the API and maintainability of the class. I'd recommend that you try the changes in your own project to make sure that the new design I'm suggesting is behaviorally compatible with the class as it is written now, and once you've done that, please update the pull request.

**Comment by rjschof** [comment]
Ah, okay. I received this after I sent the previous email. Thank you so
much for taking the time to evaluate the request! I'll do my best to come
up with these improvements. I don't think it'll be too difficult.

Thanks again!
Robert Schofield

**Comment by rjschof** [comment]
I have edited the TriangleShape, PolygonShape, and Polygon classes as you suggested. Issue #3  has been fixed. The convexDecomposition method in Polygon now returns a singleton a copy of itself. TriangleShape has been designed to make use of the PolygonShape class. The only change to PolygonShape was changing the Polygon field to protected visibility so subclasses can access it.

**Comment by rjschof** [comment]
I will change PolygonShape so the Polygon field is private, and add a getPolygon method instead. This whole thing as been an intriguing learning experience for me. 

I thought it would be beneficial, for the time being, to use this draw method while the draw method for PolygonShape was still in the works. Do you think it would be possible for the same algorithm I wrote in TriangleShape to draw the outline of the polygon for the PolygonShape class? If so, I'll make it so it can do that and then remove the methods from TriangleShape.

**Comment by rjschof** [comment]
This is what I came up with for the draw method in the `PolygonShape` class.

```java
   if (!getColor().isTransparent())
        {
            Path path = new Path();
            path.moveTo(polygon.get(0).x, polygon.get(0).y);
            for (int i = 0; i < polygon.size() - 1; i++)
            {
                path.lineTo(polygon.get(i + 1).x, polygon.get(i + 1).y);
                path.moveTo(polygon.get(i + 1).x, polygon.get(i + 1).y);
            }
            path.lineTo(polygon.get(0).x, polygon.get(0).y);
            path.offset(polygon.centroid().x, polygon.centroid().y);
            canvas.drawPath(path, getPaint());
        }
```

**Comment by allevato** [comment]
That'll do the trick, but the `moveTo` in the loop is unnecessary because `lineTo` has already moved you to that point. Then, the `lineTo` after the loop might be better written using the path's `close` method. Lastly, instead of offsetting the path based on the centroid of the polygon, make sure you use the shape's position (`getPosition`) since that's what the user would modify in an animation or manually.

Actually, it looks like `sofia/graphics/Stroke.java` already has an implementation of the logic that you need, so you could just copy it from there. I'm not sure why I never migrated the stroke-drawing logic over to use that code, since it's been a few years since I really touched it; all I remember is that I was working to factor out the fill/stroke logic to make it possible to do things like image/gradient fills with a common API. Clearly I was interrupted in the middle of this refactoring and never got back to it ¯\\\_(ツ)\_/¯

**Comment by rjschof** [comment]
Okay, I edited [TriangleShape](https://github.com/rjschof/sofia-graphics/blob/master/src/sofia/graphics/TriangleShape.java) to be nothing more than the two constructors. [PolygonShape](https://github.com/rjschof/sofia-graphics/blob/master/src/sofia/graphics/PolygonShape.java) now has the proper algorithm to draw the stroke in its draw method, and the visibility of the Polygon field was changed back to `private`. Lastly, a comment in the [Stroke](https://github.com/rjschof/sofia-graphics/blob/master/src/sofia/graphics/Stroke.java) was edited to reflect the actual functionality of the method it was referring to.

**Comment by allevato** [comment]
Looks good. Thanks again for contributing, and for making those changes (and for fixing a couple things I had left undone)!

**Comment by rjschof** [comment]
Awesome! You're welcome for the help, and thank you for taking the time to look over my pull request and for guiding me in the right direction! :)

**Pull request merged**
